function test () {
    return [
        {"inputs":[{"internalType":"string","name":"serial","type":"string"}],"name":"NftItem","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[{"internalType":"string","name":"serial","type":"string"}],"name":"SuggestItem","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[{"internalType":"string","name":"serial","type":"string"}],"name":"MarketItemData","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[],"name":"onlyManager","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[],"name":"isManager","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[],"name":"onlyOwner","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[{"internalType":"string","name":"addr","type":"string"}],"name":"setOwner","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[{"internalType":"string","name":"addr","type":"string"}],"name":"setManager","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[{"internalType":"string","name":"nftAddress","type":"string"},{"internalType":"string","name":"owner","type":"string"},{"internalType":"string","name":"to","type":"string"},{"internalType":"string","name":"tokenId","type":"string"}],"name":"transferFrom","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[{"internalType":"string","name":"nftAddress","type":"string"},{"internalType":"string","name":"tokenId","type":"string"},{"internalType":"string","name":"currency","type":"string"}],"name":"getItemSuggestionInfos","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[],"name":"getMarketDataContractAddress","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[],"name":"getMarketFee","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[],"name":"getRoyaltyFee","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[{"internalType":"string","name":"nftAddress","type":"string"},{"internalType":"string","name":"tokenId","type":"string"},{"internalType":"string","name":"suggestBiddingPrice","type":"string"},{"internalType":"string","name":"currency","type":"string"}],"name":"suggestItemToBuyWithSuggester","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[{"internalType":"string","name":"nftAddress","type":"string"},{"internalType":"string","name":"tokenId","type":"string"},{"internalType":"string","name":"currency","type":"string"},{"internalType":"string","name":"suggestBiddingPrice","type":"string"}],"name":"cancelItemToBuyWithSuggester","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[{"internalType":"string","name":"nftAddress","type":"string"},{"internalType":"string","name":"tokenId","type":"string"},{"internalType":"string","name":"suggestedBiddingPrice","type":"string"},{"internalType":"string","name":"currency","type":"string"}],"name":"acceptItemToBuyWithSeller","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[{"internalType":"string","name":"nftAddress","type":"string"},{"internalType":"string","name":"tokenId","type":"string"},{"internalType":"string","name":"buyNowPrice","type":"string"},{"internalType":"string","name":"currency","type":"string"},{"internalType":"string","name":"openTimeUtc","type":"string"},{"internalType":"string","name":"closeTimeUtc","type":"string"}],"name":"registerMarketItem","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[{"internalType":"string","name":"nftAddress","type":"string"},{"internalType":"string","name":"tokenId","type":"string"}],"name":"cancelMarketItem","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[{"internalType":"string","name":"nftAddress","type":"string"},{"internalType":"string","name":"tokenId","type":"string"},{"internalType":"string","name":"amount","type":"string"},{"internalType":"string","name":"currency","type":"string"}],"name":"buyNowWithToken","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[{"internalType":"string","name":"newFee","type":"string"}],"name":"setMarketFee","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[{"internalType":"string","name":"newFee","type":"string"}],"name":"setRoyaltyFee","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[{"internalType":"string","name":"marketData","type":"string"}],"name":"setMandatoryMarketDataContract","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[{"internalType":"string","name":"currency","type":"string"}],"name":"approveFeesForERC20Token","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
        {"inputs":[{"internalType":"string","name":"currency","type":"string"}],"name":"collectFees","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"}
    ]
}